### ISSUE TITLE
No luck getting this to work.

### ISSUE THREAD

**Issue by bootrino** [bevry/istextorbinary#247] opened 2021-09-09 21:57 UTC
I'm keen to use this as it looks like a great package.

It would be greatly helpful if there was a very plain and simple create-react-app example for typescript that showed this working.

There's so many options and variants on how to install and use it and nothing I tried resulted in a working outcome after a day.

**Comment by balupton** [comment] 2021-09-10 01:25
Your trying to use this on the client side (aka in a web browser)?

**Comment by balupton** [comment] 2021-09-10 03:47
Dupe of #246

**Closed by balupton** 2021-09-10 03:47 UTC
